# Generated by Django 4.0.2 on 2022-02-24 19:56

from django.db import migrations, models
import django.db.models.deletion
from django.core.management import call_command

def load_user_fixtures(apps, schema_editor):
    call_command('loaddata', 'user', app_label='filter_history')

def load_keyword_fixtures(apps, schema_editor):
    call_command('loaddata', 'keyword', app_label='filter_history')

def load_result_fixtures(apps, schema_editor):
    call_command('loaddata', 'result', app_label='filter_history')

def load_history_fixtures(apps, schema_editor):
    call_command('loaddata', 'history', app_label='filter_history')

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip_address', models.CharField(max_length=39, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_result', models.CharField(max_length=255, unique=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='filter_history.keyword')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now=True)),
                ('date', models.DateField(auto_now=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='filter_history.keyword')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='filter_history.user')),
            ],
        ),
        migrations.RunPython(load_user_fixtures),
        migrations.RunPython(load_keyword_fixtures),
        migrations.RunPython(load_result_fixtures),
        migrations.RunPython(load_history_fixtures),
    ]
